<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $title; ?></title>
</head>
<body>
    <?= $this->include('template/header'); ?>
    <div class="about-section">
    </br>
        <h1><center>Pemrograman Web - Pertemuan 12</center></h1>
    </br> </br> </br> </br>
        <center><img src="logo.png" height="250" width="300" align="middle">></center>
    </br> </br> </br> </br>
    </div>

    <p3><center> RIZAL GUNAWAN</br></br> Kelas TI.19.B.1</br></br> NIM 311910798 </center></p3>
    
    <?= $this->include('template/footer'); ?>
</body>
</html>
